- name: install mongodb
  hosts: mongodb
  become: yes 
  tasks: 
    - name: intalling mongodb
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: copying  mongo repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo 

    - name: enable mongodb
      ansible.builtin.service:
        name: mongod
        enabled: yes
        state: started
    
    - name: allowing remote connection  
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    
    - name: restart straing mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted
    
